### ISSUE TITLE
[Path to prod] Audit clr.fund contract and review their project format

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#106]
This ticket would be helpful to do before deploying Grant Hub MVP to production so we can be aware of and use the same schema

**Comment by schultztimothy** [comment]
Looking through clr fund's [metadata-registry](https://github.com/clrfund/metadata-registry/blob/main/docs/poster-content-layout.md) an integration with the grant hub would not be that difficult. Since their projects are all event based and indexed within a subgraph, we could query a project's metadata from their sub graph and populate our project form with their values.

Here is a list of their current schema:
## Create Metadata

| Property           | Type      | Value    |
| ------------------ |:------:| --------    |
| type               | String | metadata    |
| action             | String | create - create a metadata |
| name               | String | metadata name    |
| description        | String | markdown formatted metadata description |
| imageHash          | String | IPFS hash |
| imageUrl           | String | url |
| tagline            | String | tagline for your metadata |
| category           | String | Content, Data, Tooling  |
| problemSpace       | String | problem space description |
| plans              | String | plans |
| teamName           | String | team name |
| teamDescription    | String | team description |
| receivingAddresses | Array  | [EIP-3770](https://eips.ethereum.org/EIPS/eip-3770) addresses, i.e. eth:0x1234...789  |
| githubUrl          | String | github url |
| radicleUrl         | String | radicle url |
| websiteUrl         | String | website url |
| twitterUrl         | String | twitter url |
| discordUrl         | String | discord url |
| bannerImageHash    | String | IPFS hash |
| bannerImageUrl     | String | banner image url |
| thumbnailImageHash | String | IPFS hash |
| thumbnailImageUrl  | String | thumbnail image url |

To allow this workflow we would have to update the schema we store on IPFS to match what CLR fund is using. This can be completed after deploying our contract.

I'm not sure about other integration ideas, it may be possible to also publish grants to the clr.fund, but I believe they have a staking requirement and not sure if thats a priority.

Open to other ideas!
