### ISSUE TITLE
Verify credentials inputted by project owner (i.e. Twitter, Github)

### ISSUE THREAD

**Issue by michellema1208** [gitcoinco/grant-hub#35]
**Problem**: When a project owner enters a Twitter handle or Github account link, we need to verify that they actually own or control that account. 

For Optimism's RPGF Round, they are looking for verification that could either be through app auth or through posting from the account & scraping on Optimism side to verify. 

**Question**: What is the technical feasibility of verifying these credentials (i.e. Twitter, Github)? What is the job to be done, and what are some proposed implementations? 

Notes
- need to check what we can do on the app frontend
- could sync up with Passport team on verified credentials

**Comment by schultztimothy** [comment]
After looking into this more, it seems like this verification step needs to happen somewhere on the round manager side. In the end a user is able to submit whatever data they chose to the round application. We can do verification on the client side, but there is always the possibility of submitting the application on chain via etherscan.

As part of the application we can require a tweet be sent out from the account and include a link to that tweet in the application. 

Then when the round operator is validating applications they can verify the account in question. There could also be scripts written to do this validation for the round operator then mark the twitter account as verified based on the response. 

Since the Passport does not expose the account/PII associated with a stamp it does not look like it could be used to validate the account associated with an application.
